language: python
sudo: false

python:
  - 2.7
  - 3.5

os:
  - linux
  - osx

# matrix:
#   include:
#     - os: linux
#       env: PYTHON_VERSION=2
#     - os: linux
#       env: PYTHON_VERSION=3
#     - os: osx
#       env: PYTHON_VERSION=2
#     - os: osx
#       env: PYTHON_VERSION=3

before_install:
  - source ci/install_python.sh

install:
  - which python
  - pip freeze
  - python setup.py sdist bdist_wheel
  - pip install dist/*.tar.gz
  - pip freeze

script:
  - source ci/download_test_data.sh
  - py.test -s -vv --pyarg word2vec
